/**
 * ChittyID Service Module
 * Consolidated from id.chitty.cc worker
 * Handles ChittyID generation with pipeline-only architecture
 */

export async function handleID(context) {
  const { request, cache } = context;
  const url = new URL(request.url);
  const path = url.pathname.replace("/api/id", "");

  // Health check
  if (path === "/health") {
    return new Response(
      JSON.stringify({
        service: "chitty-id",
        status: "healthy",
        mode: "pipeline-only",
        version: "2.1.0",
      }),
      {
        headers: { "content-type": "application/json" },
      },
    );
  }

  // Generate ChittyID endpoint (pipeline-only)
  if (path === "/generate" && request.method === "POST") {
    try {
      const body = await request.json().catch(() => ({}));
      const { metadata = {}, sessionContext = {} } = body;

      // Validate API key from request headers
      const apiKey = request.headers
        .get("authorization")
        ?.replace("Bearer ", "");
      if (!apiKey) {
        return new Response(
          JSON.stringify({
            error: "API key required",
            message: "Include Authorization: Bearer <api-key> header",
          }),
          {
            status: 401,
            headers: { "content-type": "application/json" },
          },
        );
      }

      // PIPELINE ONLY - Forward request to central ChittyID service at id.chitty.cc
      // NEVER generate locally - always proxy to the central authority
      const chittyIdResponse = await fetch("https://id.chitty.cc/v1/mint", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          entityType: metadata.entityType || "INFO",
          metadata,
          sessionContext,
        }),
      });

      if (!chittyIdResponse.ok) {
        return new Response(
          JSON.stringify({
            error: "ChittyID service unavailable",
            message: `Central service returned ${chittyIdResponse.status}`,
            service: "id.chitty.cc",
            note: "ChittyIDs can ONLY be generated by the central service",
          }),
          {
            status: 502,
            headers: { "content-type": "application/json" },
          },
        );
      }

      const result = await chittyIdResponse.json();

      // Cache the result locally for fast lookup
      if (result.chittyId && Object.keys(metadata).length > 0) {
        await cache.set(
          result.chittyId,
          JSON.stringify({
            metadata,
            sessionContext,
            created: new Date().toISOString(),
            source: "id.chitty.cc",
          }),
          "id",
          86400,
        ); // 24 hour cache
      }

      return new Response(
        JSON.stringify({
          ...result,
          source: "id.chitty.cc",
          pipeline: "chittychat-proxy",
          note: "Generated by central ChittyID authority",
        }),
        {
          headers: { "content-type": "application/json" },
        },
      );
    } catch (error) {
      return new Response(
        JSON.stringify({
          error: "ChittyID proxy failed",
          message: error.message,
          note: "Cannot generate ChittyIDs locally - service must be available",
        }),
        {
          status: 500,
          headers: { "content-type": "application/json" },
        },
      );
    }
  }

  // Validate ChittyID endpoint
  if (path.startsWith("/validate/") && request.method === "GET") {
    const chittyId = path.replace("/validate/", "");

    // Use the proper validation function
    const { validateChittyIDFormat } = await import(
      "../lib/chittyid-service.js"
    );
    const isValidFormat = validateChittyIDFormat(chittyId);

    if (!chittyId || !isValidFormat) {
      return new Response(
        JSON.stringify({
          valid: false,
          error: "Invalid ChittyID format - must be VV-G-LLL-SSSS-T-YM-C-X",
        }),
        {
          headers: { "content-type": "application/json" },
        },
      );
    }

    try {
      // Check if we have metadata for this ID
      const metadata = await cache.get(chittyId, "id");
      const hasMetadata = !!metadata;

      return new Response(
        JSON.stringify({
          valid: isValidFormat,
          chittyId,
          hasMetadata,
          format: "VV-G-LLL-SSSS-T-YM-C-X",
        }),
        {
          headers: { "content-type": "application/json" },
        },
      );
    } catch (error) {
      return new Response(
        JSON.stringify({
          valid: false,
          error: "Validation failed",
          message: error.message,
        }),
        {
          status: 500,
          headers: { "content-type": "application/json" },
        },
      );
    }
  }

  // Get ChittyID metadata endpoint
  if (path.startsWith("/metadata/") && request.method === "GET") {
    const chittyId = path.replace("/metadata/", "");

    try {
      const metadata = await cache.get(chittyId, "id");

      if (!metadata) {
        return new Response(
          JSON.stringify({
            error: "Metadata not found",
            chittyId,
          }),
          {
            status: 404,
            headers: { "content-type": "application/json" },
          },
        );
      }

      return new Response(metadata, {
        headers: { "content-type": "application/json" },
      });
    } catch (error) {
      return new Response(
        JSON.stringify({
          error: "Metadata retrieval failed",
          message: error.message,
        }),
        {
          status: 500,
          headers: { "content-type": "application/json" },
        },
      );
    }
  }

  return new Response(
    JSON.stringify({
      error: "Endpoint not found",
      available: ["/health", "/generate", "/validate/{id}", "/metadata/{id}"],
      mode: "pipeline-only",
    }),
    {
      status: 404,
      headers: { "content-type": "application/json" },
    },
  );
}
