#!/bin/bash

# Connect local ChittyChat to GitHub chittyos/chittychat
# This script sets up the repository connection and branch syncing

echo "🔗 Connecting ChittyChat repositories..."

# Configuration
GITHUB_REPO="chittyos/chittychat"
LOCAL_PATH="/Users/nb/.claude/projects/-/chittychat"

# Initialize git if needed
cd "$LOCAL_PATH"
if [ ! -d .git ]; then
    echo "📦 Initializing git repository..."
    git init
    git config user.name "ChittyChat Bot"
    git config user.email "bot@chittychat.legal"
fi

# Add GitHub remote
echo "🌐 Adding GitHub remote..."
git remote add origin "https://github.com/$GITHUB_REPO.git" 2>/dev/null || \
    git remote set-url origin "https://github.com/$GITHUB_REPO.git"

# Fetch from GitHub
echo "📥 Fetching from GitHub..."
git fetch origin

# Check current branch
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "main")

# If no local commits, just checkout main from origin
if [ -z "$(git log --oneline 2>/dev/null)" ]; then
    echo "🔄 Checking out main branch from GitHub..."
    git checkout -b main origin/main
else
    echo "🔀 Setting up branch tracking..."
    git branch --set-upstream-to=origin/main main
fi

# Create session branch for current work
SESSION_ID=$(date +%s | md5sum | cut -c1-8)
SESSION_BRANCH="session-$SESSION_ID-$(date +%Y%m%d)"

echo "🌿 Creating session branch: $SESSION_BRANCH"
git checkout -b "$SESSION_BRANCH"

# Push session branch to GitHub
echo "📤 Pushing session branch to GitHub..."
git push -u origin "$SESSION_BRANCH"

# Create PR automatically
echo "🔄 Creating pull request..."
gh pr create \
    --repo "$GITHUB_REPO" \
    --title "Session: ChittyChat updates $(date +%Y-%m-%d)" \
    --body "## Session Branch: $SESSION_BRANCH

This branch contains updates from the current ChittyChat session.

### Changes
- Branch management workflows added
- Automated sync and merge capabilities
- Cron-based divergence checking

### Auto-merge
This PR will be auto-merged after 3 days if all checks pass.

---
Generated by ChittyChat Session Manager" \
    --head "$SESSION_BRANCH" \
    --base main

echo "✅ Repository connection established!"
echo ""
echo "📊 Status:"
echo "  - GitHub repo: $GITHUB_REPO"
echo "  - Session branch: $SESSION_BRANCH"
echo "  - Auto-sync enabled via GitHub Actions"
echo ""
echo "🔄 Branch management will:"
echo "  - Check divergence hourly"
echo "  - Auto-merge safe PRs every 6 hours"
echo "  - Clean stale branches daily"
echo "  - Sync session branches every 30 minutes"