#!/bin/bash
#
# ChittyOS Auto-Heal Script - Critical Issues P0/P1
# Generated by Platform Guardian - October 6, 2025
# Remediates critical compliance and infrastructure issues
#
# Usage:
#   ./scripts/auto-heal-critical-issues.sh [--dry-run] [--verbose]
#
# Options:
#   --dry-run    Show what would be done without making changes
#   --verbose    Show detailed output
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DRY_RUN=false
VERBOSE=false

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
for arg in "$@"; do
  case $arg in
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --verbose)
      VERBOSE=true
      shift
      ;;
    *)
      echo "Unknown option: $arg"
      echo "Usage: $0 [--dry-run] [--verbose]"
      exit 1
      ;;
  esac
done

log() {
  echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $*"
}

success() {
  echo -e "${GREEN}✅${NC} $*"
}

warn() {
  echo -e "${YELLOW}⚠️${NC}  $*"
}

error() {
  echo -e "${RED}❌${NC} $*"
}

run_command() {
  local cmd="$1"
  local description="$2"

  if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}[DRY-RUN]${NC} Would run: $cmd"
    return 0
  fi

  if [ "$VERBOSE" = true ]; then
    log "Running: $cmd"
  fi

  if eval "$cmd"; then
    success "$description"
    return 0
  else
    error "$description failed"
    return 1
  fi
}

check_requirements() {
  log "Checking requirements..."

  local missing_requirements=false

  # Check for required commands
  for cmd in curl jq git npm wrangler; do
    if ! command -v "$cmd" &> /dev/null; then
      error "Required command not found: $cmd"
      missing_requirements=true
    fi
  done

  # Check for CHITTY_ID_TOKEN
  if [ -z "${CHITTY_ID_TOKEN:-}" ]; then
    error "CHITTY_ID_TOKEN environment variable not set"
    missing_requirements=true
  fi

  if [ "$missing_requirements" = true ]; then
    error "Missing requirements. Please install missing tools and set environment variables."
    exit 1
  fi

  success "All requirements met"
}

# P0-1: Check DNS configuration
check_dns_issues() {
  log "Checking DNS configuration for ChittyOS services..."

  local services=(
    "register.chitty.cc"
    "gateway.chitty.cc"
    "schema.chitty.cc"
  )

  local dns_issues=()

  for service in "${services[@]}"; do
    log "Testing $service..."

    local status_code
    status_code=$(curl -s -o /dev/null -w "%{http_code}" "https://$service/health" 2>&1 || echo "000")

    if [ "$status_code" = "200" ]; then
      success "$service is healthy"
    elif [ "$status_code" = "403" ]; then
      warn "$service returns 403 Forbidden (P0-2: Authentication issue)"
      dns_issues+=("$service:403")
    elif [ "$status_code" = "000" ] || [ "$status_code" = "1000" ]; then
      error "$service is unreachable (P0-1: DNS issue)"
      dns_issues+=("$service:dns")
    else
      warn "$service returns unexpected status: $status_code"
      dns_issues+=("$service:$status_code")
    fi
  done

  if [ ${#dns_issues[@]} -gt 0 ]; then
    warn "Found ${#dns_issues[@]} DNS/connectivity issues"
    echo "Issues detected:"
    for issue in "${dns_issues[@]}"; do
      echo "  - $issue"
    done
    return 1
  else
    success "All DNS configurations appear healthy"
    return 0
  fi
}

# P0-2: Check gateway authentication
fix_gateway_auth() {
  log "Checking gateway.chitty.cc authentication..."

  # Test health endpoint (should not require auth)
  local status_code
  status_code=$(curl -s -o /dev/null -w "%{http_code}" "https://gateway.chitty.cc/health" 2>&1)

  if [ "$status_code" = "403" ]; then
    warn "Gateway returns 403 - attempting fixes..."

    # Check wrangler deployment status
    log "Checking current deployment..."
    if run_command "wrangler deployments list --name chittyos-platform-prod 2>&1 | head -10" "List deployments"; then
      # Redeploy if needed
      if [ "$DRY_RUN" = false ]; then
        warn "Attempting redeployment to fix gateway auth..."
        cd "$PROJECT_ROOT"
        npm run deploy:production
        success "Gateway redeployed"

        # Wait for propagation
        sleep 10

        # Retest
        status_code=$(curl -s -o /dev/null -w "%{http_code}" "https://gateway.chitty.cc/health" 2>&1)
        if [ "$status_code" = "200" ]; then
          success "Gateway auth fixed!"
          return 0
        else
          error "Gateway still returns $status_code after redeployment"
          return 1
        fi
      fi
    fi
  elif [ "$status_code" = "200" ]; then
    success "Gateway authentication is working"
    return 0
  else
    warn "Gateway returns unexpected status: $status_code"
    return 1
  fi
}

# P1-3: Fix test infrastructure
fix_test_infrastructure() {
  log "Checking test infrastructure..."

  local test_script="$PROJECT_ROOT/scripts/test-services.js"

  if [ ! -f "$test_script" ]; then
    warn "Test script missing: $test_script"

    if [ "$DRY_RUN" = false ]; then
      log "Creating test script..."

      mkdir -p "$PROJECT_ROOT/scripts"

      cat > "$test_script" << 'TESTEOF'
/**
 * ChittyOS Services Test Suite
 * Generated by auto-heal script
 */

const services = [
  { name: 'ChittyID', url: 'https://id.chitty.cc/health' },
  { name: 'Registry', url: 'https://registry.chitty.cc/health' },
  { name: 'Canon', url: 'https://canon.chitty.cc/health' },
  { name: 'Register', url: 'https://register.chitty.cc/health' },
  { name: 'Gateway', url: 'https://gateway.chitty.cc/health' },
  { name: 'Schema', url: 'https://schema.chitty.cc/health' },
];

async function testService(service) {
  try {
    const response = await fetch(service.url);
    const status = response.status;
    const ok = response.ok;

    console.log(`${ok ? '✅' : '❌'} ${service.name}: ${status}`);

    if (ok) {
      const data = await response.json();
      console.log(`   Version: ${data.version || 'unknown'}`);
    }

    return ok;
  } catch (error) {
    console.log(`❌ ${service.name}: ${error.message}`);
    return false;
  }
}

async function runTests() {
  console.log('ChittyOS Services Health Test\n');

  let passed = 0;
  let failed = 0;

  for (const service of services) {
    const result = await testService(service);
    if (result) {
      passed++;
    } else {
      failed++;
    }
  }

  console.log(`\nResults: ${passed} passed, ${failed} failed`);

  if (failed > 0) {
    process.exit(1);
  }
}

runTests().catch(error => {
  console.error('Test suite failed:', error);
  process.exit(1);
});
TESTEOF

      chmod +x "$test_script"
      success "Test script created: $test_script"

      # Run tests
      log "Running new test suite..."
      node "$test_script"
    else
      echo "[DRY-RUN] Would create $test_script"
    fi
  else
    success "Test script exists: $test_script"

    # Run tests
    log "Running test suite..."
    if [ "$DRY_RUN" = false ]; then
      node "$test_script"
    else
      echo "[DRY-RUN] Would run: node $test_script"
    fi
  fi
}

# P1-1: Check for rogue ChittyID patterns
check_rogue_patterns() {
  log "Checking for rogue ChittyID generation patterns..."

  cd "$PROJECT_ROOT"

  # Run ChittyCheck focused on ID patterns
  log "Running ChittyCheck ID pattern validation..."

  local violations
  violations=$(grep -r "Math\.random()" --include="*.js" --include="*.ts" . \
    | grep -i "chittyid\|generate.*id" \
    | grep -v node_modules \
    | grep -v ".git" \
    | grep -v "auto-heal" \
    | wc -l | tr -d ' ')

  if [ "$violations" -gt 0 ]; then
    warn "Found $violations potential rogue ID generation patterns"

    echo "Sample violations:"
    grep -r "Math\.random()" --include="*.js" --include="*.ts" . \
      | grep -i "chittyid\|generate.*id" \
      | grep -v node_modules \
      | grep -v ".git" \
      | grep -v "auto-heal" \
      | head -5

    warn "Run './chittyfix-id-patterns.sh' to automatically fix these violations"
    return 1
  else
    success "No obvious rogue ID patterns detected"
    return 0
  fi
}

# Run ChittyCheck full validation
run_chittycheck() {
  log "Running full ChittyCheck validation..."

  local chittycheck_script="/Users/nb/.claude/projects/-/chittychat/chittycheck-enhanced.sh"

  if [ -f "$chittycheck_script" ]; then
    if [ "$DRY_RUN" = false ]; then
      bash "$chittycheck_script" || {
        warn "ChittyCheck found issues"
        return 1
      }
    else
      echo "[DRY-RUN] Would run: $chittycheck_script"
    fi
  else
    warn "ChittyCheck script not found: $chittycheck_script"
    return 1
  fi
}

# Generate compliance report
generate_report() {
  log "Generating compliance report..."

  local report_file="$PROJECT_ROOT/auto-heal-report-$(date +%Y%m%d-%H%M%S).json"

  local dns_status="unknown"
  local gateway_status="unknown"
  local test_status="unknown"
  local patterns_status="unknown"

  # Check DNS
  if check_dns_issues > /dev/null 2>&1; then
    dns_status="healthy"
  else
    dns_status="issues"
  fi

  # Check gateway
  local gateway_code
  gateway_code=$(curl -s -o /dev/null -w "%{http_code}" "https://gateway.chitty.cc/health" 2>&1)
  if [ "$gateway_code" = "200" ]; then
    gateway_status="healthy"
  else
    gateway_status="issues"
  fi

  # Check test infrastructure
  if [ -f "$PROJECT_ROOT/scripts/test-services.js" ]; then
    test_status="present"
  else
    test_status="missing"
  fi

  # Check patterns
  local pattern_count
  pattern_count=$(grep -r "Math\.random()" --include="*.js" --include="*.ts" . \
    | grep -i "chittyid\|generate.*id" \
    | grep -v node_modules \
    | grep -v ".git" \
    | wc -l | tr -d ' ')

  if [ "$pattern_count" -eq 0 ]; then
    patterns_status="clean"
  else
    patterns_status="violations:$pattern_count"
  fi

  cat > "$report_file" << REPORTEOF
{
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "platform": "ChittyOS",
  "audit_version": "2025-10-06",
  "auto_heal_run": $([ "$DRY_RUN" = true ] && echo "false" || echo "true"),
  "issues": {
    "dns_configuration": "$dns_status",
    "gateway_authentication": "$gateway_status",
    "test_infrastructure": "$test_status",
    "rogue_id_patterns": "$patterns_status"
  },
  "services": {
    "id.chitty.cc": "$(curl -s -o /dev/null -w "%{http_code}" "https://id.chitty.cc/health" 2>&1)",
    "registry.chitty.cc": "$(curl -s -o /dev/null -w "%{http_code}" "https://registry.chitty.cc/health" 2>&1)",
    "canon.chitty.cc": "$(curl -s -o /dev/null -w "%{http_code}" "https://canon.chitty.cc/health" 2>&1)",
    "register.chitty.cc": "$(curl -s -o /dev/null -w "%{http_code}" "https://register.chitty.cc/health" 2>&1)",
    "gateway.chitty.cc": "$(curl -s -o /dev/null -w "%{http_code}" "https://gateway.chitty.cc/health" 2>&1)",
    "schema.chitty.cc": "$(curl -s -o /dev/null -w "%{http_code}" "https://schema.chitty.cc/health" 2>&1)"
  },
  "next_steps": [
    "Fix DNS issues manually via Cloudflare Dashboard",
    "Run chittyfix-id-patterns.sh for compliance violations",
    "Deploy fixed services with npm run deploy:production",
    "Verify with ChittyCheck: chittycheck-enhanced.sh"
  ]
}
REPORTEOF

  success "Report generated: $report_file"

  if command -v jq &> /dev/null; then
    echo ""
    log "Report summary:"
    jq . "$report_file"
  fi
}

# Main execution
main() {
  echo ""
  echo "════════════════════════════════════════════════════════════"
  echo "  ChittyOS Auto-Heal - Critical Issues P0/P1"
  echo "  Generated by Platform Guardian - October 6, 2025"
  echo "════════════════════════════════════════════════════════════"
  echo ""

  if [ "$DRY_RUN" = true ]; then
    warn "DRY-RUN MODE: No changes will be made"
    echo ""
  fi

  # Step 1: Check requirements
  check_requirements
  echo ""

  # Step 2: Check DNS issues (P0-1)
  log "🔍 Step 1: Checking DNS configuration..."
  if check_dns_issues; then
    success "DNS checks passed"
  else
    warn "DNS issues detected - manual intervention required"
    echo "   → Open Cloudflare Dashboard to fix DNS records"
    echo "   → See PLATFORM_AUDIT_REPORT_2025-10-06.md for details"
  fi
  echo ""

  # Step 3: Check/fix gateway auth (P0-2)
  log "🔍 Step 2: Checking gateway authentication..."
  if fix_gateway_auth; then
    success "Gateway authentication verified"
  else
    warn "Gateway issues detected"
  fi
  echo ""

  # Step 4: Check/fix test infrastructure (P1-3)
  log "🔍 Step 3: Checking test infrastructure..."
  if fix_test_infrastructure; then
    success "Test infrastructure verified"
  else
    warn "Test infrastructure issues detected"
  fi
  echo ""

  # Step 5: Check for rogue patterns (P1-1)
  log "🔍 Step 4: Checking for rogue ChittyID patterns..."
  if check_rogue_patterns; then
    success "No rogue patterns detected"
  else
    warn "Rogue patterns found - run chittyfix-id-patterns.sh"
  fi
  echo ""

  # Step 6: Run full ChittyCheck
  log "🔍 Step 5: Running full ChittyCheck validation..."
  if run_chittycheck; then
    success "ChittyCheck validation passed"
  else
    warn "ChittyCheck found issues"
  fi
  echo ""

  # Step 7: Generate report
  generate_report
  echo ""

  echo "════════════════════════════════════════════════════════════"
  log "Auto-heal complete!"
  echo ""
  echo "Next steps:"
  echo "  1. Review audit report: PLATFORM_AUDIT_REPORT_2025-10-06.md"
  echo "  2. Fix remaining DNS issues via Cloudflare Dashboard"
  echo "  3. Run chittyfix-id-patterns.sh for compliance violations"
  echo "  4. Deploy changes: npm run deploy:production"
  echo "  5. Verify: /Users/nb/.claude/projects/-/chittychat/chittycheck-enhanced.sh"
  echo "════════════════════════════════════════════════════════════"
  echo ""
}

# Run main function
main "$@"
